uniqueness_check:: has been FAIL
Details: for column: last_name and the count is {'customer_id': 0, 'first_name': 2, 'last_name': 1}

